Shopping cart model
vfilimo/book-store pull request #13
Opened 2024-09-17 12:33 UTC by vfilimo

2024-09-18 09:56 UTC, MentorMateAcademy requested changes

2024-09-18 09:56 UTC, MentorMateAcademy commented on src/main/java/online/store/book/repository/cart/ShoppingCartRepository.java
> +@Repository
```suggestion
```

2024-09-18 09:56 UTC, MentorMateAcademy commented on src/main/java/online/store/book/repository/user/RoleRepository.java
>  @Repository
```suggestion
```

2024-09-19 07:36 UTC, liliia-ponomarenko requested changes
Good job! Let's improve your solution;)

2024-09-19 07:36 UTC, liliia-ponomarenko commented on src/main/java/online/store/book/controller/ShoppingCartController.java
> +        String email = getEmailFromContext();
better use of user ID because search by identifier has better performance

2024-09-19 07:36 UTC, liliia-ponomarenko commented on src/main/java/online/store/book/controller/ShoppingCartController.java
> +    @DeleteMapping("/items/{cartItemId}")
Better use ResponseStatus.No_CONTENT

2024-09-19 07:36 UTC, liliia-ponomarenko commented on src/main/java/online/store/book/repository/user/RoleRepository.java
> +    @Query("SELECT r FROM Role r WHERE r.name = :name")
Why do you need query here?

2024-09-19 07:36 UTC, liliia-ponomarenko commented on src/main/java/online/store/book/repository/cart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findAllFieldsByUserEmail(@Param("email") String email);
```suggestion
    Optional<ShoppingCart> findByUserEmail(@Param("email") String email);
```

2024-09-19 07:36 UTC, liliia-ponomarenko commented on src/main/java/online/store/book/service/cart/ShoppingCartServiceImpl.java
> +                    () -> new EntityNotFoundException("You don't have shopping cart")
```suggestion
                    () -> new EntityNotFoundException(User: "
                        + email + " doesn't have shopping cart")
```

2024-09-19 07:36 UTC, liliia-ponomarenko commented on src/main/java/online/store/book/controller/ShoppingCartController.java
> +            @PathVariable Long cartItemId, @RequestBody int quantity) {
You should create requstDto class and validate quantity input value

2024-09-19 18:47 UTC, okuzan approved these changes

2024-09-19 18:47 UTC, okuzan commented on src/main/java/online/store/book/service/cart/ShoppingCartServiceImpl.java
> +                );
better extract to a private method

2024-09-19 18:47 UTC, okuzan commented on src/main/java/online/store/book/model/ShoppingCart.java
> +@SQLRestriction("is_deleted = false")
```suggestion
@SQLDelete(sql = "UPDATE shopping_carts SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction("is_deleted = FALSE")
```

2024-09-20 09:33 UTC, merged