Order model
vfilimo/book-store pull request #14
Opened 2024-09-20 09:40 UTC by vfilimo

2024-09-20 12:43 UTC, Elena-Bruyako requested changes
see comments

2024-09-20 12:43 UTC, Elena-Bruyako commented on src/main/java/online/store/book/controller/OrderController.java
> +    OrderResponseDto placeOrder(@RequestBody @Valid OrderRequestDto orderRequestDto) {
```suggestion
    public OrderResponseDto placeOrder(@RequestBody @Valid OrderRequestDto orderRequestDto) {
```

for all endpoints

2024-09-20 12:43 UTC, Elena-Bruyako commented on src/main/java/online/store/book/repository/order/OrderRepository.java
> +    Optional<OrderItem> findItemById(
it should be in OrderItemRepo
Also, check this query without any EntityGraph 

```
@Query(value = """
            SELECT oi FROM OrderItem oi
            JOIN FETCH oi.order o
            WHERE oi.id = :orderItemId AND o.id = :orderId AND o.user.id = :userId""")
    Optional<OrderItem> findByIdAndOrderIdAndUserId(@Param("orderItemId") Long orderItemId,
                                                    @Param("orderId") Long orderId,
                                                    @Param("userId") Long userId);
```

2024-09-20 12:43 UTC, Elena-Bruyako commented on src/main/java/online/store/book/service/order/OrderServiceImpl.java
> +        Set<OrderItem> orderItems = shoppingCart.getCartItems().stream()
what if shoppingCart.getCartItems() is empty?

2024-09-20 12:43 UTC, Elena-Bruyako commented on src/main/java/online/store/book/service/order/OrderServiceImpl.java
> +    private ShoppingCart getShoppingCartByUser(User user) {
private methods should be placed after public methods

2024-09-20 12:43 UTC, Elena-Bruyako commented on src/main/java/online/store/book/repository/order/OrderRepository.java
> +    Page<Order> findByUserId(@Param("userId") Long userId, Pageable pageable);
```suggestion
    @EntityGraph(attributePaths = "orderItems")
    List<Order> findAllByUserId(Long userId, Pageable pageable);
```

2024-09-20 12:43 UTC, Elena-Bruyako commented on src/main/java/online/store/book/service/order/OrderServiceImpl.java
> +        OrderItem orderItem = orderRepository.findItemById(user.getId(), orderId, itemId)
Simpler 

`OrderItem item = orderItemRepository.findByIdAndOrderIdAndUserId(orderItemId, orderId, userId)`

2024-09-20 12:43 UTC, Elena-Bruyako commented on src/main/java/online/store/book/service/order/OrderServiceImpl.java
> +                orderRepository.findItemsById(user.getId(), orderId, pageable));
```suggestion
                Order order = orderRepository.findByIdAndUserId(orderId, userId)...
                return orderItemMapper.toOrderItemDtoList(order.getOrderItems());
```

where 

```
@EntityGraph(attributePaths = "orderItems")
Optional<Order> findByIdAndUserId(Long orderId, Long userId);
```

2024-09-22 18:51 UTC, Elena-Bruyako requested changes
see comments

2024-09-22 18:51 UTC, Elena-Bruyako commented on src/main/java/online/store/book/exceptions/EmptyCartException.java
> +public class EmptyCartException extends RuntimeException {
```suggestion
public class OrderProcessingException extends RuntimeException {
```

2024-09-22 18:51 UTC, Elena-Bruyako commented on src/main/java/online/store/book/exceptions/EmptyCartException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
```suggestion
```

2024-09-24 10:19 UTC, okuzan approved these changes

2024-09-29 09:49 UTC, merged