Add docker
vfilimo/book-store pull request #15
Opened 2024-09-21 14:59 UTC by vfilimo

2024-09-22 18:54 UTC, Elena-Bruyako requested changes
see comment

2024-09-22 18:54 UTC, Elena-Bruyako commented on .env
> +MYSQLDB_USER=user
it's better to create .env.sample file without properties and add .env to gitignore

2024-09-23 10:56 UTC, okuzan approved these changes

2024-09-23 10:56 UTC, okuzan commented on .env.sample
> +SPRING_DOCKER_PORT
```suggestion
SPRING_DOCKER_PORT=
```

2024-09-29 10:13 UTC, merged