App testing
vfilimo/book-store pull request #16
Opened 2024-09-29 10:18 UTC by vfilimo

![coverage](https://github.com/user-attachments/assets/ca031d66-44fc-411d-b4e2-28f65e7db6b6)

2024-09-30 10:28 UTC, MentorMateAcademy requested changes

2024-09-30 10:28 UTC, MentorMateAcademy commented on src/test/java/online/store/book/service/book/BookServiceImplTest.java
> +    @InjectMocks
inject mocks after mocks

2024-09-30 10:28 UTC, MentorMateAcademy commented on src/test/java/online/store/book/service/book/BookServiceImplTest.java
> +    private Pageable pageable;
let`s build this entities by private methods

2024-10-01 07:41 UTC, liliia-ponomarenko requested changes
Good job! Let's improve your solution ;)

2024-10-01 07:41 UTC, liliia-ponomarenko commented on src/test/java/online/store/book/controller/BookControllerIntegrationTest.java
> +class BookControllerIntegrationTest {
Let's remove Integration. You don't have any other type of tests for Controller ) 
```suggestion
class BookControllerTest {
```

2024-10-01 07:41 UTC, liliia-ponomarenko commented on src/test/java/online/store/book/controller/BookControllerIntegrationTest.java
> +                    new ClassPathResource("db/books/add_books_for_Integration_Test.sql"));
use a uniform naming style for files
```suggestion
                    new ClassPathResource("db/books/add-books-for-integration-test.sql"));
```

2024-10-01 07:41 UTC, liliia-ponomarenko commented on src/test/java/online/store/book/BookRepositoryTest.java
> +        assertEquals("Horror Stories", actualTitle);
This is a rather strange check that relies on the sequence of elements in the collection. Why then do we validate the author and not the title of the book?

2024-10-01 07:41 UTC, liliia-ponomarenko commented on src/test/java/online/store/book/BookRepositoryTest.java
> +        assertFalse(isPresent);
The same. Better get the content of the Page and check that size == 0

2024-10-01 07:41 UTC, liliia-ponomarenko commented on src/test/java/online/store/book/controller/BookControllerIntegrationTest.java
> +        MvcResult result = mockMvc.perform(post("/books")
this literal should be constant

2024-10-01 07:41 UTC, liliia-ponomarenko commented on src/test/java/online/store/book/controller/CategoryControllerIntegrationTest.java
> +            teardown(dataSource);
Why do you need this check? If you need this logic for a specific test use it above the test

2024-10-01 07:41 UTC, liliia-ponomarenko commented on src/test/java/online/store/book/controller/CategoryControllerIntegrationTest.java
> +                .andReturn();
what are you testing here? security? 
Do you need to test the filter chain in this class?

2024-10-01 07:41 UTC, liliia-ponomarenko commented on src/test/java/online/store/book/service/book/BookServiceImplTest.java
> +    private Pageable pageable;
no need to take it to the class level, it's better for each of your tests to have its own object, so just call the private method of creating the object in the appropriate tests

2024-10-01 07:41 UTC, liliia-ponomarenko commented on src/test/java/online/store/book/service/category/CategoryServiceImplTest.java
> +
the same

2024-10-01 15:43 UTC, vfilimo commented on src/test/java/online/store/book/controller/CategoryControllerIntegrationTest.java
> +            teardown(dataSource);
I need this check to do the setup for all methods except one.

2024-10-02 08:57 UTC, okuzan commented on src/test/java/online/store/book/controller/CategoryControllerIntegrationTest.java
> +            teardown(dataSource);
This approach looks fragile to me - depends of display name wording. Let's use something more solid, try smth like this
![image](https://github.com/user-attachments/assets/6fb0211a-11d3-4669-9f20-493807b9d155)
https://www.baeldung.com/junit-filtering-tests

2024-10-02 08:58 UTC, okuzan requested changes
left a suggestion for test filtering

2024-10-03 08:00 UTC, okuzan approved these changes

2024-10-03 09:28 UTC, merged