Book controller
vfilimo/book-store pull request #2
Opened 2024-08-11 14:11 UTC by vfilimo

2024-08-11 18:00 UTC, Elena-Bruyako requested changes
see comments

2024-08-11 18:00 UTC, Elena-Bruyako commented on pom.xml
> +					<source>${java.version}</source> <!-- depending on your project -->
remove comments

2024-08-11 18:00 UTC, Elena-Bruyako commented on src/main/java/online/store/book/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-08-11 18:00 UTC, Elena-Bruyako commented on src/main/java/online/store/book/repository/BookRepositoryImpl.java
> +            throw new DataProcessingException("Can't find book with id: " + id + " in the DB", e);
```suggestion
             return Optional.ofNullable(session.get(Book.class, id));
        } catch (Exception e) {
            throw new DataProcessingException("Can't find book with id: " + id + " in the DB", e);
        }
```

2024-08-11 18:00 UTC, Elena-Bruyako commented on src/main/java/online/store/book/service/BookServiceImpl.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-08-11 18:00 UTC, Elena-Bruyako commented on src/main/java/online/store/book/service/BookServiceImpl.java
> +
```suggestion
```

2024-08-12 07:43 UTC, okuzan approved these changes

2024-08-12 08:30 UTC, merged