Liquibase support and repo refactor
vfilimo/book-store pull request #3
Opened 2024-08-20 09:02 UTC by vfilimo

2024-08-20 21:19 UTC, sarakhmen requested changes
let's improve your solution :)

2024-08-20 21:19 UTC, sarakhmen commented on src/main/java/online/store/book/service/BookServiceImpl.java
> +        findBookById(id);
why do you have this method call here? Seems to be redundant. Fix in all places

2024-08-20 21:19 UTC, sarakhmen commented on src/main/java/online/store/book/service/BookServiceImpl.java
> +        Book bookEntity = bookMapper.toEntity(bookRequestDto);
We recommend making all request mappings at the controller level. Fix in all places

2024-08-22 12:44 UTC, Elena-Bruyako requested changes
see comments

2024-08-22 12:44 UTC, Elena-Bruyako commented on src/main/java/online/store/book/service/BookServiceImpl.java
> +        bookRepository.findById(id).orElseThrow(
```suggestion
        Book book = bookRepository.findById(id).orElseThrow(
```

2024-08-22 12:44 UTC, Elena-Bruyako commented on src/main/java/online/store/book/service/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(bookEntity));
```suggestion
        bookMapper.updateBookFromDto(bookRequestDto, book);
        return bookMapper.toDto(bookRepository.save(book));
```

2024-08-22 12:44 UTC, Elena-Bruyako commented on src/main/java/online/store/book/service/BookServiceImpl.java
> +                () -> new EntityNotFoundException("Can't find book with id: " + id));
```suggestion
```

2024-08-22 14:50 UTC, Elena-Bruyako approved these changes

2024-08-22 15:41 UTC, merged