Pagination sorting swagger
vfilimo/book-store pull request #6
Opened 2024-08-28 14:20 UTC by vfilimo

2024-08-28 19:46 UTC, sarakhmen requested changes
good job, let's slightly improve your solution :)

2024-08-28 19:46 UTC, sarakhmen commented on pom.xml
> +
```suggestion
```

2024-08-28 19:46 UTC, sarakhmen commented on src/main/java/online/store/book/controller/BookController.java
> +    public List<BookDto> getAll(Pageable pageable) {
please add default pageable values, fix in all places

2024-08-29 11:43 UTC, Elena-Bruyako requested changes
one spelling mistake

2024-08-29 11:43 UTC, Elena-Bruyako commented on src/main/java/online/store/book/controller/BookController.java
> +            description = "Get all books by tittle and author")
```suggestion
            description = "Get all books by title and author")
```

2024-08-29 13:14 UTC, Elena-Bruyako approved these changes
well done

2024-08-29 14:28 UTC, merged