Security
vfilimo/book-store pull request #8
Opened 2024-09-07 11:27 UTC by vfilimo

2024-09-08 09:17 UTC, okuzan requested changes

2024-09-08 09:17 UTC, okuzan commented on src/main/resources/db/changelog/changes/07-insert-users.yaml
> +                  value: $2a$10$zFoOVRbOX39EDGXC0endRuqO9hvXIaW/EuP0ZCH0waHL7bIgBZ8uu
add password in plain text as comment next to this value

2024-09-08 09:17 UTC, okuzan commented on src/main/java/online/store/book/config/SecurityConfig.java
> +                                .requestMatchers("/api/auth/register", "/error",
```suggestion
                                .requestMatchers("/auth/**", "/error",
```
don't hardcode context prefix + login should be excluded too

2024-09-08 15:36 UTC, Elena-Bruyako requested changes
see comments

2024-09-08 15:36 UTC, Elena-Bruyako commented on src/main/java/online/store/book/model/Role.java
> +        return name.toString();
```suggestion
        return name.name();
```

2024-09-08 15:36 UTC, Elena-Bruyako commented on src/main/java/online/store/book/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany
```

2024-09-08 15:36 UTC, Elena-Bruyako commented on src/main/java/online/store/book/model/User.java
> +    private Set<Role> roles;
```suggestion
    private Set<Role> roles = new HashSet<>();
```

2024-09-08 15:36 UTC, Elena-Bruyako commented on src/main/java/online/store/book/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2024-09-08 15:36 UTC, Elena-Bruyako commented on src/main/java/online/store/book/security/CustomUserDetailsService.java
> +                () -> new UsernameNotFoundException("Can't find user by email: " + email));
```suggestion
                () -> new EntityNotFoundException("Can't find user by email: " + email));
```

2024-09-08 15:36 UTC, Elena-Bruyako commented on src/main/java/online/store/book/security/CustomUserDetailsService.java
> +    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String email) {
```

2024-09-08 15:36 UTC, Elena-Bruyako commented on src/main/java/online/store/book/security/CustomUserDetailsService.java
> +        return userRepository.findUserByEmail(email).orElseThrow(
Add to UserRepository method with annotation

```
@EntityGraph(attributePaths = "roles")
Optional<User> findByEmail(String email);
```

2024-09-08 15:36 UTC, Elena-Bruyako commented on src/main/java/online/store/book/exceptions/CustomGlobalExceptionHandler.java
> +    @ExceptionHandler(UsernameNotFoundException.class)
```suggestion
    @ExceptionHandler(EntityNotFoundException.class)
```

2024-09-08 15:36 UTC, Elena-Bruyako commented on src/main/java/online/store/book/exceptions/CustomGlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleUsernameNotFoundException(
rename

2024-09-08 15:36 UTC, Elena-Bruyako commented on src/main/java/online/store/book/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
You should also implement other controller with POST: /api/auth/register 
for more details check task description

2024-09-09 11:43 UTC, vfilimo commented on src/main/java/online/store/book/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
discussed in chat

2024-09-09 12:16 UTC, Elena-Bruyako approved these changes
well done

2024-09-09 12:37 UTC, merged